import type { ContentTitle } from '@streambrws/shared-types';

export const MOCK_TITLES: ContentTitle[] = [
  { id: 'n1', serviceId: 'netflix', externalId: 'nf-001', title: 'Dark Kingdoms', description: 'A sprawling medieval fantasy epic following warring dynasties across three continents.', type: 'series', genres: ['fantasy', 'drama', 'action'], tags: ['violence', 'mature'], rating: 'TV-MA', year: 2024, posterUrl: 'https://picsum.photos/seed/dk/200/290', backdropUrl: 'https://picsum.photos/seed/dkb/800/450', deepLinkUrl: 'netflix://title/nf-001' },
  { id: 'n2', serviceId: 'netflix', externalId: 'nf-002', title: 'The Last Signal', description: 'A lone astronaut receives a mysterious transmission from beyond the solar system.', type: 'movie', genres: ['sci-fi', 'thriller'], tags: [], rating: 'PG-13', year: 2025, posterUrl: 'https://picsum.photos/seed/ls/200/290', deepLinkUrl: 'netflix://title/nf-002' },
  { id: 'n3', serviceId: 'netflix', externalId: 'nf-003', title: 'Comedy Nights', description: 'Stand-up specials from the world\'s top comedians, recorded live.', type: 'special', genres: ['comedy'], tags: ['adult'], rating: 'TV-MA', year: 2025, posterUrl: 'https://picsum.photos/seed/cn/200/290', deepLinkUrl: 'netflix://title/nf-003' },
  { id: 'h1', serviceId: 'hulu', externalId: 'hu-001', title: 'Neon City Blues', description: 'A neo-noir detective series set in a rain-soaked cyberpunk metropolis.', type: 'series', genres: ['crime', 'sci-fi', 'drama'], tags: ['violence'], rating: 'TV-14', year: 2025, posterUrl: 'https://picsum.photos/seed/nc/200/290', deepLinkUrl: 'hulu://title/hu-001' },
  { id: 'h2', serviceId: 'hulu', externalId: 'hu-002', title: 'Family Ties Reunion', description: 'A heartwarming dramedy about three estranged siblings who must return home.', type: 'series', genres: ['drama', 'comedy'], tags: [], rating: 'TV-PG', year: 2024, posterUrl: 'https://picsum.photos/seed/ft/200/290', deepLinkUrl: 'hulu://title/hu-002' },
  { id: 'hb1', serviceId: 'hbo_max', externalId: 'hbo-001', title: 'Empire of Ash', description: 'A post-apocalyptic epic charting the rise of new civilizations after a global collapse.', type: 'series', genres: ['sci-fi', 'drama', 'action'], tags: ['violence', 'war'], rating: 'TV-MA', year: 2026, posterUrl: 'https://picsum.photos/seed/ea/200/290', deepLinkUrl: 'max://title/hbo-001' },
  { id: 'hb2', serviceId: 'hbo_max', externalId: 'hbo-002', title: 'The Diplomat\'s Wife', description: 'A gripping political thriller set against the backdrop of international espionage.', type: 'series', genres: ['political', 'thriller'], tags: ['political'], rating: 'TV-14', year: 2025, posterUrl: 'https://picsum.photos/seed/dw/200/290', deepLinkUrl: 'max://title/hbo-002' },
  { id: 'd1', serviceId: 'disney_plus', externalId: 'dp-001', title: 'Galaxy Rangers', description: 'Young heroes from across the galaxy unite to defend the universe from an ancient evil.', type: 'series', genres: ['animation', 'adventure', 'sci-fi'], tags: [], rating: 'PG', year: 2025, posterUrl: 'https://picsum.photos/seed/gr/200/290', deepLinkUrl: 'disneyplus://title/dp-001' },
  { id: 'd2', serviceId: 'disney_plus', externalId: 'dp-002', title: 'Wilderness: Untouched', description: 'An immersive nature documentary exploring Earth\'s last pristine wilderness areas.', type: 'documentary', genres: ['documentary', 'nature'], tags: [], rating: 'G', year: 2024, posterUrl: 'https://picsum.photos/seed/wu/200/290', deepLinkUrl: 'disneyplus://title/dp-002' },
  { id: 'a1', serviceId: 'amazon_prime', externalId: 'ap-001', title: 'Merchant Kings', description: 'A sweeping historical drama set during the height of the spice trade era.', type: 'series', genres: ['historical', 'drama', 'adventure'], tags: [], rating: 'TV-14', year: 2025, posterUrl: 'https://picsum.photos/seed/mk/200/290', deepLinkUrl: 'primevideo://title/ap-001' },
  { id: 'a2', serviceId: 'amazon_prime', externalId: 'ap-002', title: 'Quantum Break', description: 'A scientist discovers a way to manipulate time, with catastrophic consequences.', type: 'movie', genres: ['sci-fi', 'thriller', 'action'], tags: ['violence'], rating: 'PG-13', year: 2026, posterUrl: 'https://picsum.photos/seed/qb/200/290', deepLinkUrl: 'primevideo://title/ap-002' },
  { id: 'at1', serviceId: 'apple_tv', externalId: 'atv-001', title: 'The Architects', description: 'A slow-burn drama following the visionary designers who shaped modern cities.', type: 'series', genres: ['drama'], tags: [], rating: 'TV-14', year: 2025, posterUrl: 'https://picsum.photos/seed/ta/200/290', deepLinkUrl: 'appletv://title/atv-001' },
  { id: 'pp1', serviceId: 'paramount_plus', externalId: 'par-001', title: 'Deep State', description: 'An intelligence thriller uncovering shadowy forces inside government agencies.', type: 'series', genres: ['political', 'thriller', 'crime'], tags: ['political'], rating: 'TV-MA', year: 2025, posterUrl: 'https://picsum.photos/seed/ds/200/290', deepLinkUrl: 'paramountplus://title/par-001' },
  { id: 'pc1', serviceId: 'peacock', externalId: 'pea-001', title: 'Real Housewives: Malibu', description: 'Reality drama following the lives of affluent residents along the Malibu coast.', type: 'series', genres: ['reality-tv', 'drama'], tags: ['reality-tv'], rating: 'TV-14', year: 2025, posterUrl: 'https://picsum.photos/seed/rhm/200/290', deepLinkUrl: 'peacocktv://title/pea-001' },
  { id: 'sw1', serviceId: 'showtime', externalId: 'sh-001', title: 'Blood Brothers', description: 'A gritty crime drama about rival crime families in 1970s Chicago.', type: 'series', genres: ['crime', 'drama', 'violence'], tags: ['violence', 'adult'], rating: 'TV-MA', year: 2024, posterUrl: 'https://picsum.photos/seed/bb/200/290', deepLinkUrl: 'showtime://title/sh-001' },
  { id: 'st1', serviceId: 'starz', externalId: 'sz-001', title: 'The Highland Saga', description: 'An epic period drama set in 18th century Scotland, following clan warfare and romance.', type: 'series', genres: ['historical', 'drama', 'romance'], tags: [], rating: 'TV-MA', year: 2025, posterUrl: 'https://picsum.photos/seed/hs/200/290', deepLinkUrl: 'starz://title/sz-001' },
];
